---
- name: Squid Setup
  block:
    - name: Install Squid
      ansible.builtin.apt:
        name: squid
        state: present
        update_cache: yes

    - name: Ensure Squid is running and enabled
      ansible.builtin.service:
        name: squid
        state: started
        enabled: yes

    - name: Hold Squid version
      ansible.builtin.dpkg_selections:
        name: squid
        selection: hold

    - name: Copy custom squid.conf
      ansible.builtin.copy:
        src: ./configs/squid.conf
        dest: /etc/squid/squid.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Squid
