{{- with .Values.apps }}
{{- if .victoriaMetrics.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .victoriaMetrics.metadata.name }}
  namespace: {{ $.Values.namespace | default "argocd" }}
{{- with .victoriaMetrics.spec }}
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ $.Values.targetRevision | default "HEAD" }}
    path: {{ .source.path }}
    helm:
      {{- if .valueFiles }}
      valueFiles:
        {{- toYaml .valueFiles | nindent 8 }}
      {{- end }}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    {{- toYaml .syncPolicy | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
