{{- with .Values.apps }}
{{- if .addons.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-lab
  namespace: {{ $.Values.namespace | default "argocd" }}
{{- with .addons.spec }}
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ $.Values.targetRevision | default "HEAD" }}
    path: {{ .source.path }}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    {{- toYaml .syncPolicy | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
