{{- if .Values.projects.addons}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
spec:
  destinations:
    - name: in-cluster
      namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
{{- end }}

---
{{- if .Values.projects.workspaceLab}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workspace-lab
spec:
  destinations:
    - name: in-cluster
      namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
{{- end }}
