---
- name: Common Setup
  block:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure required packages is installed
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present
